export enum OnboardingStatus {
  PLAN_REQUIRED = 'PLAN_REQUIRED',
  WORKSPACE_ACTIVATION = 'WORKSPACE_ACTIVATION',
  PROFILE_CREATION = 'PROFILE_CREATION',
  SYNC_EMAIL = 'SYNC_EMAIL',
  APPS_INSTALLATION = 'APPS_INSTALLATION',
  INVITE_TEAM = 'INVITE_TEAM',
  BOOK_CALL = 'BOOK_CALL',
  COMPLETED = 'COMPLETED',

  // Achare onboarding statuses
  ACHARE_WELCOME = 'ACHARE_WELCOME',
  ACHARE_BASIC_SETUP = 'ACHARE_BASIC_SETUP',
  ACHARE_SETUP_CHOICE = 'ACHARE_SETUP_CHOICE',
  ACHARE_AGENCY = 'ACHARE_AGENCY',
  ACHARE_TEAM = 'ACHARE_TEAM',
  ACHARE_CRM_IMPORT = 'ACHARE_CRM_IMPORT',
  ACHARE_RECRUITMENT = 'ACHARE_RECRUITMENT',
  ACHARE_HR = 'ACHARE_HR',
  ACHARE_PAYROLL = 'ACHARE_PAYROLL',
  ACHARE_DASHBOARD = 'ACHARE_DASHBOARD',
  ACHARE_REVIEW = 'ACHARE_REVIEW',
}
