export enum AchareSetupStepKeys {
  ACHARE_SETUP_STATUS = 'ACHARE_SETUP_STATUS',
  ACHARE_SETUP_MODE = 'ACHARE_SETUP_MODE',
  ACHARE_SETUP_CURRENT_STEP = 'ACHARE_SETUP_CURRENT_STEP',
  ACHARE_BASIC_SETUP_COMPLETED = 'ACHARE_BASIC_SETUP_COMPLETED',
  ACHARE_AGENCY_COMPLETED = 'ACHARE_AGENCY_COMPLETED',
  ACHARE_TEAM_COMPLETED = 'ACHARE_TEAM_COMPLETED',
  ACHARE_CRM_IMPORT_COMPLETED = 'ACHARE_CRM_IMPORT_COMPLETED',
  ACHARE_RECRUITMENT_COMPLETED = 'ACHARE_RECRUITMENT_COMPLETED',
  ACHARE_HR_COMPLETED = 'ACHARE_HR_COMPLETED',
  ACHARE_HR_SKIPPED = 'ACHARE_HR_SKIPPED',
  ACHARE_PAYROLL_COMPLETED = 'ACHARE_PAYROLL_COMPLETED',
  ACHARE_PAYROLL_SKIPPED = 'ACHARE_PAYROLL_SKIPPED',
  ACHARE_DASHBOARD_COMPLETED = 'ACHARE_DASHBOARD_COMPLETED',
  ACHARE_SETUP_COMPLETED_AT = 'ACHARE_SETUP_COMPLETED_AT',
  ACHARE_SETUP_VERSION = 'ACHARE_SETUP_VERSION',
}

export type AchareSetupStatus = 'NOT_STARTED' | 'IN_PROGRESS' | 'COMPLETED';

export type AchareSetupMode = 'GUIDED' | 'MANUAL';

export type AchareSetupStep =
  | 'WELCOME'
  | 'BASIC_SETUP'
  | 'SETUP_CHOICE'
  | 'AGENCY'
  | 'TEAM'
  | 'CRM_IMPORT'
  | 'RECRUITMENT'
  | 'HR'
  | 'PAYROLL'
  | 'DASHBOARD'
  | 'REVIEW';

export const ACHARE_SETUP_STEPS_ORDER: AchareSetupStep[] = [
  'WELCOME',
  'BASIC_SETUP',
  'SETUP_CHOICE',
  'AGENCY',
  'TEAM',
  'CRM_IMPORT',
  'RECRUITMENT',
  'HR',
  'PAYROLL',
  'DASHBOARD',
  'REVIEW',
];

export const ACHARE_SETUP_CURRENT_VERSION = 1;
