import { AppPath } from 'twenty-shared/types';

export const ONBOARDING_PATHS = [
  AppPath.WorkspaceActivation,
  AppPath.CreateProfile,
  AppPath.SyncEmails,
  AppPath.InstallApps,
  AppPath.InviteTeam,
  AppPath.PlanRequired,
  AppPath.PlanRequiredSuccess,
  AppPath.BookCall,
  AppPath.AchareWelcome,
  AppPath.AchareBasicSetup,
  AppPath.AchareSetupChoice,
  AppPath.AchareFeatureSelection,
  AppPath.AchareAgency,
  AppPath.AchareTeam,
  AppPath.AchareCrmImport,
  AppPath.AchareRecruitment,
  AppPath.AchareHr,
  AppPath.AcharePayroll,
  AppPath.AchareFinance,
  AppPath.AchareDocuments,
  AppPath.AchareDashboard,
  AppPath.AchareReview,
];
