//the higher the number, the higher the priority
export const STANDARD_OBJECTS_BY_PRIORITY_RANK = {
  person: 5,
  company: 4,
  opportunity: 3,
  employee: 3,
  candidate: 3,
  requirement: 3,
  note: 2,
  task: 2,
  department: 2,
  team: 2,
  candidateSubmission: 2,
  interview: 2,
  invoice: 2,
  designation: 1,
  location: 1,
  shift: 1,
  rosterAssignment: 1,
  attendanceDay: 1,
  leaveRequest: 1,
  leaveBalance: 1,
  salaryStructure: 1,
  payrollPeriod: 1,
  payslip: 1,
  payrollAdjustment: 1,
  payment: 1,
  onboardingItem: 1,
};
