import { type AchareOnboardingStepKey } from '../constants/AchareOnboardingSteps';

/**
 * The step that follows `currentStep` in a workspace's *dynamic* step list.
 *
 * This is what makes the wizard adapt: the caller passes the list generated by
 * `getAchareOnboardingSteps(enabledFeatures)`, so a step that does not exist
 * for this workspace is never the answer. A step absent from the list (because
 * a module was disabled after onboarding started) resolves to the next step
 * that does exist rather than dead-ending.
 *
 * Returns `null` when the list is exhausted — the caller then finishes
 * onboarding.
 */
export const getNextAchareOnboardingStep = (
  steps: AchareOnboardingStepKey[],
  currentStep: AchareOnboardingStepKey | null | undefined,
): AchareOnboardingStepKey | null => {
  if (currentStep === null || currentStep === undefined) {
    return steps[0] ?? null;
  }

  const currentIndex = steps.indexOf(currentStep);

  if (currentIndex === -1) {
    // The current step is not part of this workspace's list — a module was
    // disabled after onboarding started, or legacy state was read. Restarting
    // from the top is the one deterministic, always-valid answer; anything
    // cleverer would guess at a position we cannot know.
    return steps[0] ?? null;
  }

  return steps[currentIndex + 1] ?? null;
};
