import { type FlatViewField } from 'src/engine/metadata-modules/flat-view-field/types/flat-view-field.type';
import {
  createStandardViewFieldFlatMetadata,
  type CreateStandardViewFieldArgs,
} from 'src/engine/workspace-manager/twenty-standard-application/utils/view-field/create-standard-view-field-flat-metadata.util';

export const computeStandardInterviewViewFields = (
  args: Omit<CreateStandardViewFieldArgs<'interview'>, 'context'>,
): Record<string, FlatViewField> => {
  return {
    // byScheduledAt (Calendar View) fields - only 4 fields defined in STANDARD_OBJECTS
    byScheduledAtTitle: createStandardViewFieldFlatMetadata({
      ...args,
      objectName: 'interview',
      context: {
        viewName: 'byScheduledAt',
        viewFieldName: 'title',
        fieldName: 'title',
        position: 0,
        isVisible: true,
        isCalendarImportant: true,
        size: 150,
      },
    }),
    byScheduledAtCandidate: createStandardViewFieldFlatMetadata({
      ...args,
      objectName: 'interview',
      context: {
        viewName: 'byScheduledAt',
        viewFieldName: 'candidate',
        fieldName: 'candidate',
        position: 1,
        isVisible: true,
        isCalendarImportant: true,
        size: 150,
      },
    }),
    byScheduledAtScheduledAt: createStandardViewFieldFlatMetadata({
      ...args,
      objectName: 'interview',
      context: {
        viewName: 'byScheduledAt',
        viewFieldName: 'scheduledAt',
        fieldName: 'scheduledAt',
        position: 2,
        isVisible: true,
        isCalendarImportant: false,
        size: 150,
      },
    }),
    byScheduledAtMode: createStandardViewFieldFlatMetadata({
      ...args,
      objectName: 'interview',
      context: {
        viewName: 'byScheduledAt',
        viewFieldName: 'mode',
        fieldName: 'mode',
        position: 3,
        isVisible: true,
        isCalendarImportant: false,
        size: 100,
      },
    }),

    // allInterviews (Table View) fields
    allInterviewsTitle: createStandardViewFieldFlatMetadata({
      ...args,
      objectName: 'interview',
      context: {
        viewName: 'allInterviews',
        viewFieldName: 'title',
        fieldName: 'title',
        position: 0,
        isVisible: true,
        size: 150,
      },
    }),
    allInterviewsRound: createStandardViewFieldFlatMetadata({
      ...args,
      objectName: 'interview',
      context: {
        viewName: 'allInterviews',
        viewFieldName: 'round',
        fieldName: 'round',
        position: 1,
        isVisible: true,
        size: 100,
      },
    }),
    allInterviewsStatus: createStandardViewFieldFlatMetadata({
      ...args,
      objectName: 'interview',
      context: {
        viewName: 'allInterviews',
        viewFieldName: 'status',
        fieldName: 'status',
        position: 2,
        isVisible: true,
        size: 100,
      },
    }),
    allInterviewsResult: createStandardViewFieldFlatMetadata({
      ...args,
      objectName: 'interview',
      context: {
        viewName: 'allInterviews',
        viewFieldName: 'result',
        fieldName: 'result',
        position: 3,
        isVisible: true,
        size: 100,
      },
    }),
    allInterviewsInterviewer: createStandardViewFieldFlatMetadata({
      ...args,
      objectName: 'interview',
      context: {
        viewName: 'allInterviews',
        viewFieldName: 'interviewer',
        fieldName: 'interviewer',
        position: 4,
        isVisible: true,
        size: 120,
      },
    }),
    allInterviewsScheduledAt: createStandardViewFieldFlatMetadata({
      ...args,
      objectName: 'interview',
      context: {
        viewName: 'allInterviews',
        viewFieldName: 'scheduledAt',
        fieldName: 'scheduledAt',
        position: 5,
        isVisible: true,
        size: 150,
      },
    }),
    allInterviewsMode: createStandardViewFieldFlatMetadata({
      ...args,
      objectName: 'interview',
      context: {
        viewName: 'allInterviews',
        viewFieldName: 'mode',
        fieldName: 'mode',
        position: 6,
        isVisible: true,
        size: 100,
      },
    }),
    allInterviewsMeetingLink: createStandardViewFieldFlatMetadata({
      ...args,
      objectName: 'interview',
      context: {
        viewName: 'allInterviews',
        viewFieldName: 'meetingLink',
        fieldName: 'meetingLink',
        position: 7,
        isVisible: true,
        size: 150,
      },
    }),
    allInterviewsSubmission: createStandardViewFieldFlatMetadata({
      ...args,
      objectName: 'interview',
      context: {
        viewName: 'allInterviews',
        viewFieldName: 'submission',
        fieldName: 'submission',
        position: 8,
        isVisible: true,
        size: 150,
      },
    }),
    allInterviewsRequirement: createStandardViewFieldFlatMetadata({
      ...args,
      objectName: 'interview',
      context: {
        viewName: 'allInterviews',
        viewFieldName: 'requirement',
        fieldName: 'requirement',
        position: 9,
        isVisible: true,
        size: 150,
      },
    }),
    allInterviewsCandidate: createStandardViewFieldFlatMetadata({
      ...args,
      objectName: 'interview',
      context: {
        viewName: 'allInterviews',
        viewFieldName: 'candidate',
        fieldName: 'candidate',
        position: 10,
        isVisible: true,
        size: 150,
      },
    }),
    allInterviewsCompany: createStandardViewFieldFlatMetadata({
      ...args,
      objectName: 'interview',
      context: {
        viewName: 'allInterviews',
        viewFieldName: 'company',
        fieldName: 'company',
        position: 11,
        isVisible: true,
        size: 150,
      },
    }),
    allInterviewsOwner: createStandardViewFieldFlatMetadata({
      ...args,
      objectName: 'interview',
      context: {
        viewName: 'allInterviews',
        viewFieldName: 'owner',
        fieldName: 'owner',
        position: 12,
        isVisible: true,
        size: 150,
      },
    }),
    allInterviewsFeedback: createStandardViewFieldFlatMetadata({
      ...args,
      objectName: 'interview',
      context: {
        viewName: 'allInterviews',
        viewFieldName: 'feedback',
        fieldName: 'feedback',
        position: 13,
        isVisible: true,
        size: 150,
      },
    }),
    allInterviewsCreatedAt: createStandardViewFieldFlatMetadata({
      ...args,
      objectName: 'interview',
      context: {
        viewName: 'allInterviews',
        viewFieldName: 'createdAt',
        fieldName: 'createdAt',
        position: 14,
        isVisible: true,
        size: 150,
      },
    }),
    allInterviewsCreatedBy: createStandardViewFieldFlatMetadata({
      ...args,
      objectName: 'interview',
      context: {
        viewName: 'allInterviews',
        viewFieldName: 'createdBy',
        fieldName: 'createdBy',
        position: 15,
        isVisible: true,
        size: 150,
      },
    }),
    allInterviewsUpdatedAt: createStandardViewFieldFlatMetadata({
      ...args,
      objectName: 'interview',
      context: {
        viewName: 'allInterviews',
        viewFieldName: 'updatedAt',
        fieldName: 'updatedAt',
        position: 16,
        isVisible: true,
        size: 150,
      },
    }),
    allInterviewsUpdatedBy: createStandardViewFieldFlatMetadata({
      ...args,
      objectName: 'interview',
      context: {
        viewName: 'allInterviews',
        viewFieldName: 'updatedBy',
        fieldName: 'updatedBy',
        position: 17,
        isVisible: true,
        size: 150,
      },
    }),
    allInterviewsDeletedAt: createStandardViewFieldFlatMetadata({
      ...args,
      objectName: 'interview',
      context: {
        viewName: 'allInterviews',
        viewFieldName: 'deletedAt',
        fieldName: 'deletedAt',
        position: 18,
        isVisible: false,
        size: 150,
      },
    }),
    allInterviewsAttachments: createStandardViewFieldFlatMetadata({
      ...args,
      objectName: 'interview',
      context: {
        viewName: 'allInterviews',
        viewFieldName: 'attachments',
        fieldName: 'attachments',
        position: 19,
        isVisible: false,
        size: 150,
      },
    }),
    allInterviewsNotes: createStandardViewFieldFlatMetadata({
      ...args,
      objectName: 'interview',
      context: {
        viewName: 'allInterviews',
        viewFieldName: 'notes',
        fieldName: 'notes',
        position: 20,
        isVisible: false,
        size: 150,
      },
    }),
    allInterviewsTimelineActivities: createStandardViewFieldFlatMetadata({
      ...args,
      objectName: 'interview',
      context: {
        viewName: 'allInterviews',
        viewFieldName: 'timelineActivities',
        fieldName: 'timelineActivities',
        position: 21,
        isVisible: false,
        size: 150,
      },
    }),
    allInterviewsInterviewParticipants: createStandardViewFieldFlatMetadata({
      ...args,
      objectName: 'interview',
      context: {
        viewName: 'allInterviews',
        viewFieldName: 'interviewParticipants',
        fieldName: 'interviewParticipants',
        position: 22,
        isVisible: false,
        size: 150,
      },
    }),
    allInterviewsTaskTargets: createStandardViewFieldFlatMetadata({
      ...args,
      objectName: 'interview',
      context: {
        viewName: 'allInterviews',
        viewFieldName: 'taskTargets',
        fieldName: 'taskTargets',
        position: 23,
        isVisible: false,
        size: 150,
      },
    }),
    allInterviewsNoteTargets: createStandardViewFieldFlatMetadata({
      ...args,
      objectName: 'interview',
      context: {
        viewName: 'allInterviews',
        viewFieldName: 'noteTargets',
        fieldName: 'noteTargets',
        position: 24,
        isVisible: false,
        size: 150,
      },
    }),

    // interviewRecordPageFields view fields
    interviewRecordPageFieldsTitle: createStandardViewFieldFlatMetadata({
      ...args,
      objectName: 'interview',
      context: {
        viewName: 'interviewRecordPageFields',
        viewFieldName: 'title',
        fieldName: 'title',
        position: 0,
        isVisible: true,
        size: 150,
      },
    }),
    interviewRecordPageFieldsRound: createStandardViewFieldFlatMetadata({
      ...args,
      objectName: 'interview',
      context: {
        viewName: 'interviewRecordPageFields',
        viewFieldName: 'round',
        fieldName: 'round',
        position: 1,
        isVisible: true,
        size: 100,
      },
    }),
    interviewRecordPageFieldsStatus: createStandardViewFieldFlatMetadata({
      ...args,
      objectName: 'interview',
      context: {
        viewName: 'interviewRecordPageFields',
        viewFieldName: 'status',
        fieldName: 'status',
        position: 2,
        isVisible: true,
        size: 100,
      },
    }),
    interviewRecordPageFieldsResult: createStandardViewFieldFlatMetadata({
      ...args,
      objectName: 'interview',
      context: {
        viewName: 'interviewRecordPageFields',
        viewFieldName: 'result',
        fieldName: 'result',
        position: 3,
        isVisible: true,
        size: 100,
      },
    }),
    interviewRecordPageFieldsInterviewer: createStandardViewFieldFlatMetadata({
      ...args,
      objectName: 'interview',
      context: {
        viewName: 'interviewRecordPageFields',
        viewFieldName: 'interviewer',
        fieldName: 'interviewer',
        position: 4,
        isVisible: true,
        size: 120,
      },
    }),
    interviewRecordPageFieldsScheduledAt: createStandardViewFieldFlatMetadata({
      ...args,
      objectName: 'interview',
      context: {
        viewName: 'interviewRecordPageFields',
        viewFieldName: 'scheduledAt',
        fieldName: 'scheduledAt',
        position: 5,
        isVisible: true,
        size: 150,
      },
    }),
    interviewRecordPageFieldsMode: createStandardViewFieldFlatMetadata({
      ...args,
      objectName: 'interview',
      context: {
        viewName: 'interviewRecordPageFields',
        viewFieldName: 'mode',
        fieldName: 'mode',
        position: 6,
        isVisible: true,
        size: 100,
      },
    }),
    interviewRecordPageFieldsMeetingLink: createStandardViewFieldFlatMetadata({
      ...args,
      objectName: 'interview',
      context: {
        viewName: 'interviewRecordPageFields',
        viewFieldName: 'meetingLink',
        fieldName: 'meetingLink',
        position: 7,
        isVisible: true,
        size: 150,
      },
    }),
    interviewRecordPageFieldsFeedback: createStandardViewFieldFlatMetadata({
      ...args,
      objectName: 'interview',
      context: {
        viewName: 'interviewRecordPageFields',
        viewFieldName: 'feedback',
        fieldName: 'feedback',
        position: 8,
        isVisible: true,
        size: 150,
      },
    }),
    interviewRecordPageFieldsSubmission: createStandardViewFieldFlatMetadata({
      ...args,
      objectName: 'interview',
      context: {
        viewName: 'interviewRecordPageFields',
        viewFieldName: 'submission',
        fieldName: 'submission',
        position: 9,
        isVisible: true,
        size: 150,
      },
    }),
    interviewRecordPageFieldsRequirement: createStandardViewFieldFlatMetadata({
      ...args,
      objectName: 'interview',
      context: {
        viewName: 'interviewRecordPageFields',
        viewFieldName: 'requirement',
        fieldName: 'requirement',
        position: 10,
        isVisible: true,
        size: 150,
      },
    }),
    interviewRecordPageFieldsCandidate: createStandardViewFieldFlatMetadata({
      ...args,
      objectName: 'interview',
      context: {
        viewName: 'interviewRecordPageFields',
        viewFieldName: 'candidate',
        fieldName: 'candidate',
        position: 11,
        isVisible: true,
        size: 150,
      },
    }),
    interviewRecordPageFieldsCompany: createStandardViewFieldFlatMetadata({
      ...args,
      objectName: 'interview',
      context: {
        viewName: 'interviewRecordPageFields',
        viewFieldName: 'company',
        fieldName: 'company',
        position: 12,
        isVisible: true,
        size: 150,
      },
    }),
    interviewRecordPageFieldsOwner: createStandardViewFieldFlatMetadata({
      ...args,
      objectName: 'interview',
      context: {
        viewName: 'interviewRecordPageFields',
        viewFieldName: 'owner',
        fieldName: 'owner',
        position: 13,
        isVisible: true,
        size: 150,
      },
    }),
    interviewRecordPageFieldsAttachments: createStandardViewFieldFlatMetadata({
      ...args,
      objectName: 'interview',
      context: {
        viewName: 'interviewRecordPageFields',
        viewFieldName: 'attachments',
        fieldName: 'attachments',
        position: 14,
        isVisible: false,
        size: 150,
      },
    }),
    interviewRecordPageFieldsNotes: createStandardViewFieldFlatMetadata({
      ...args,
      objectName: 'interview',
      context: {
        viewName: 'interviewRecordPageFields',
        viewFieldName: 'notes',
        fieldName: 'notes',
        position: 15,
        isVisible: false,
        size: 150,
      },
    }),
    interviewRecordPageFieldsTimelineActivities: createStandardViewFieldFlatMetadata({
      ...args,
      objectName: 'interview',
      context: {
        viewName: 'interviewRecordPageFields',
        viewFieldName: 'timelineActivities',
        fieldName: 'timelineActivities',
        position: 16,
        isVisible: false,
        size: 150,
      },
    }),
    interviewRecordPageFieldsInterviewParticipants: createStandardViewFieldFlatMetadata({
      ...args,
      objectName: 'interview',
      context: {
        viewName: 'interviewRecordPageFields',
        viewFieldName: 'interviewParticipants',
        fieldName: 'interviewParticipants',
        position: 17,
        isVisible: false,
        size: 150,
      },
    }),
    interviewRecordPageFieldsTaskTargets: createStandardViewFieldFlatMetadata({
      ...args,
      objectName: 'interview',
      context: {
        viewName: 'interviewRecordPageFields',
        viewFieldName: 'taskTargets',
        fieldName: 'taskTargets',
        position: 18,
        isVisible: false,
        size: 150,
      },
    }),
    interviewRecordPageFieldsNoteTargets: createStandardViewFieldFlatMetadata({
      ...args,
      objectName: 'interview',
      context: {
        viewName: 'interviewRecordPageFields',
        viewFieldName: 'noteTargets',
        fieldName: 'noteTargets',
        position: 19,
        isVisible: false,
        size: 150,
      },
    }),
    interviewRecordPageFieldsCreatedAt: createStandardViewFieldFlatMetadata({
      ...args,
      objectName: 'interview',
      context: {
        viewName: 'interviewRecordPageFields',
        viewFieldName: 'createdAt',
        fieldName: 'createdAt',
        position: 20,
        isVisible: true,
        size: 150,
      },
    }),
    interviewRecordPageFieldsCreatedBy: createStandardViewFieldFlatMetadata({
      ...args,
      objectName: 'interview',
      context: {
        viewName: 'interviewRecordPageFields',
        viewFieldName: 'createdBy',
        fieldName: 'createdBy',
        position: 21,
        isVisible: true,
        size: 150,
      },
    }),
    interviewRecordPageFieldsUpdatedAt: createStandardViewFieldFlatMetadata({
      ...args,
      objectName: 'interview',
      context: {
        viewName: 'interviewRecordPageFields',
        viewFieldName: 'updatedAt',
        fieldName: 'updatedAt',
        position: 22,
        isVisible: true,
        size: 150,
      },
    }),
    interviewRecordPageFieldsUpdatedBy: createStandardViewFieldFlatMetadata({
      ...args,
      objectName: 'interview',
      context: {
        viewName: 'interviewRecordPageFields',
        viewFieldName: 'updatedBy',
        fieldName: 'updatedBy',
        position: 23,
        isVisible: true,
        size: 150,
      },
    }),
    interviewRecordPageFieldsDeletedAt: createStandardViewFieldFlatMetadata({
      ...args,
      objectName: 'interview',
      context: {
        viewName: 'interviewRecordPageFields',
        viewFieldName: 'deletedAt',
        fieldName: 'deletedAt',
        position: 24,
        isVisible: false,
        size: 150,
      },
    }),
  };
};
