export enum ViewType {
  TABLE = 'TABLE',
  KANBAN = 'KANBAN',
  CALENDAR = 'CALENDAR',
  LIST = 'LIST',
  CARD = 'CARD',
  FIELDS_WIDGET = 'FIELDS_WIDGET',
  TABLE_WIDGET = 'TABLE_WIDGET',
  KANBAN_WIDGET = 'KANBAN_WIDGET',
  LIST_WIDGET = 'LIST_WIDGET',
  CALENDAR_WIDGET = 'CALENDAR_WIDGET',
}
